language: python

python:
  - "3.6"

env:
  - DJANGO=2.0.7

services:
  - postgresql

install:
  - pip install -r requirements/ci.txt

before_script:
  - psql -c "CREATE USER travis_user WITH PASSWORD 'travis_password';" -U postgres
  - psql -c "CREATE DATABASE travis_db;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE travis_db TO travis_user;" -U postgres
  - python src/manage.py migrate

script:
  - make test

after_success:
  - coveralls
  - psql -c "DROP DATABASE travis_db;" -U postgres
  - psql -c "DROP USER travis_user;" -U postgres
