version: '3.5'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: sites
      POSTGRES_USER: sites
      POSTGRES_DB: sites
  web:
    build: .
    environment:
      PORT: 8000
      PYTHON_ENV: development
      DB_NAME: sites
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: sites
      DB_PASSWORD: sites
      SECRET_KEY: "@%%-!e^mzb0f)l5gk^a#04!("
      DEBUG: "True"
    ports:
      - "8000:8000"
    links:
      - db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
volumes:
  db_data:
